# Makefile for project 1
#
# You should not need to modify this file.

CC		= gcc

CFLAGS		= -g  -Wall

problem: problem.c
	$(CC) $(CFLAGS) -o problem problem.c

clean:
	rm -f *~ *.o a.out core problem
